variables:

  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "6514223"

before_script:

  - echo "sdk.dir=${ANDROID_HOME}" >> local.properties
  - echo "ndk.dir=${ANDROID_NDK_HOME}" >> local.properties
  - chmod +x ./gradlew
  
  # Add libnunchuk and build deps
  - pushd ${PWD}/src/main/native
  - git submodule add --force -b android_experimental https://gitlab.com/nunchuck/libnunchuk.git
  - git submodule update --init --recursive
  - sh .install_deps.sh arm64-v8a
  - popd
  - echo ${PWD}

buildAndPublishNativeSdk:
  interruptible: true
  stage: build
  script:
    - ./gradlew clean assembleArm64_v8aDebug --stacktrace
    - ./gradlew publish
