variables:

  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "6514223"

before_script:
  - echo "sdk.dir=${ANDROID_HOME}" >> local.properties
  - echo "ndk.dir=${ANDROID_NDK_HOME}" >> local.properties
  - chmod +x ./gradlew

  # Add libnunchuk and build deps
  - pushd ${PWD}/src/main/native
  - git submodule add --force -b main https://gitlab.com/nunchuck/libnunchuk.git
  - git submodule update --init --recursive
  - sh .install_deps.sh arm64-v8a
  # bash .install_linux_deps.sh arm64-v8a for linux
  - popd
  - echo ${PWD}

stages:
  - build
  - deploy

build:
  except:
    - master
  stage: build
  script:
    - ./gradlew clean assembleArm64_v8a --stacktrace

deploy:
  only:
    - master
  stage: deploy
  script:
    - ./gradlew clean assembleArm64_v8a --stacktrace
    - ./gradlew publish
